Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "vodka")
Ingredient.create(name: "lemon juice")
Ingredient.create(name: "egg white")
Ingredient.create(name: "orange zest")
Ingredient.create(name: "gin")
Ingredient.create(name: "vermouth")
Ingredient.create(name: "lemon twist")
Ingredient.create(name: "soda water")
Ingredient.create(name: "sugar")
Ingredient.create(name: "cola")
Ingredient.create(name: "sprite")
Ingredient.create(name: "fanta")
Ingredient.create(name: "rum")
Ingredient.create(name: "whiskey")
